export const articleData = [
  {
    id: 1,
    imageSource: `https://situ.nyc/img/M3ZDVk54VHRSZ0ZJZ1ZpbDl3R2JRQT09/icrc-bw.png`,
    titleText: `Basic Facts`,
    subTitleText: ` The human cost of landmines`,
    bodyText1: `Scope And Nature Of The Crisis
    Mine-laying has become common practice in virtually every conflict situation where the ICRC is present, and the institution is confronted daily with the harrowing consequences of the widespread and indiscriminate use of this deadly weapon. Mines are now proliferating so fast that there are perhaps as many as I 10 million of them spread in 64 countries worldwide, and it is estimated that 2 to 5 million more mines are being laid each year. Scattered like deadly seeds, they kill and maim between 1.000 and 2.000 people per month, most of them innocent civilians.
    With an estimated 30 million mines strewn in at least 18 countries, Africa is the continent most severely affected by the large scale sowing of landmines . The most critical situations are found in Angola with more than 9 million mines, in Mozambique with up to 2 million and in Somalia with I million. Ethiopia, Eritrea and Sudan also have to face severe situations, and countries like Rwanda, Liberia and Libya have landmine problems on a smaller scale.
    The majority of landmine victims are civilians who step on a mine after armed conflicts has ceased. In some countries, over one-third of all casualties due to landmines are women and children. Landmines are indiscriminate weapons that lie dormant until triggered, be it by a soldier, or a civilian, a friend or a foe, an adult or a child.They cause excessive suffering to the injured and their families and have devastating effects upon communi ties and their environment for decades after conflicts have ceased.`,
    bodyText2: `A Perverse Use Of Technology
    Two categories of landmines are commonly in use: large antitank mines designed to be triggered by vehicles, and the small inexpensive antipersonnel mines designed specifically to kill or incapacitate a human being. According to Human Rights Watch, more than 340 antipersonnel landmine models have been produced in at least 48 nations around the world. Their prices vary between US $ 3 and US $ 75 per unit whilst the cost of clearance estimated by the United Nations, including support and logistic costs, is between US $ 300 and US $ 1,000 per mine.
    The most common types of antipersonnel landmines are blast mines, usually designed to explode when the victim steps directly on the mine. Other types, such as directional fragmentation and bounding mines, will kill or maim not only the victim activating the mine but also anyone within its effective range. In Angola, for example, at least thirty-seven known types of landmines were used over the past twenty years. In recent decades the problems caused by landmines have been exacerbated by modem technology, such as the design of undetectable plastic blast mines which render their sighting and their removal extremely difficult. Furthermore, their small size and type of design have tended to attract children to play with them. Models such as " scatterbabies " and " butterfly mines " are cruel examples of the deceptive design.
    Danger to civilians is further increased by the development of remote-delivery methods capable of deploying enormous numbers of mines over vast tracts of land from a distance, for example by aircraft, rocket or artillery. These methods facilitate the random, undetectable an d unmapped use of landmines. In the Quito Cuanvale municipality of Angola for example, of the 330,000 mines that were sown, the location of only 80,000 is known.`,
    bodyText3: `Mine Clearance: An Urgent Necessity
    Landmines are very seldom removed. Where conflicts are raging, new mines are being laid faster than old ones are being taken out. These difficulties are compounded by the legal void as regard to responsibility for mine clearance and by the shortage of financial resources and trained personnel for such operations. Mine clearance and disposal are at present very primitive, slow and hazardous. Mechanical means which have been developed are not sufficiently effective. Modem plastic mines do not respond to metal detectors and the only sure way to clear mines is often to go across the area inch by inch, using prodders such as bayonets, knives and screwdriver-like instruments to probe the ground.
    Mine disposal experts indicate that an average of one person is killed and two are injured for every 5,000 mines cleared. These figures can be worsened in some critical situation when the training and the material is not sufficient: in early 1991, the Somali National Movement began demining in northern Somalia under the leadership of a soldier with demolition and demining training. The clearance force included 60 men; 40 % were killed or injured by mines in the first six months of the year. In Angola, according to the Department of Humanitarian Affairs of the United Nations, more than 2,000 mine clearers will be needed during a period from 6 to 10 years to obtain satisfactory results.
    According to a Report of the UN Secretary General (September 1994) " the I I 0 million landmines currently buried world-wide will cost approximately $ 33 billion for clearance alone. Last year, the international community allocated approximately $ 70 million to clear roughly 100,000 landmines. During the same period, however, roughly 2.000.000 more landmines were laid, leaving the international community with a annual " demining deficit " of some 1.900.000 mines last year, and adding another $ 1.4 billion, at the same annual cost of clearance, to the aggregate cost of clearing the world's landmines.`,
  },
  {
    id: 2,
    imageSource: `https://www.crwflags.com/fotw/images/i/int-apmbc.gif`,
    titleText: `Anti-Personnel Mine Ban Convention`,
    subTitleText: `Convention on the Prohibition of the Use, Stockpiling, Production and Transfer of Anti-Personnel Mines and on their Destruction`,
    bodyText1: `History and Text
    The Convention on the Prohibition of the Use, Stockpiling, Production and Transfer of Anti-Personnel Mines and on Their Destruction (also known as Anti-Personnel Mine Ban Convention, Ottawa Convention, or Mine Ban Treaty) is the cornerstone of the international effort to end the suffering and casualties caused by anti-personnel mines.
    The so-called Ottawa Process, was a “bold gamble” that paid off largely as a result of the advocacy work of the International Campaign to Ban Landmines and the International Committee of the Red Cross working in partnership with a core group of States that were equally committed to a ban on anti-personnel mines. This process ultimately resulted in the adoption of the Convention on 18 September 1997 in Oslo, Norway. The Convention entered into force on 1 March 1999, after the 30th State Party deposited its instrument of ratification, acceptance, approval or accession. 
    `,
    bodyText2: `What does the Convention say? 
    The Convention prohibits the use, stockpiling, production and transfer of anti-personnel mines. It also requires States Parties to destroy their stockpiles of anti-personnel mines within four years of the entry into force of the Convention for them. The Convention also requires States Parties to provide assistance to victims of anti-personnel mines and to promote mine awareness and mine risk education.
    Each State Party must make “every effort to identify all areas under its jurisdiction or control in which anti-personnel mines are known or suspected to be emplaced.” 
    It must also “take all feasible measures to destroy such mines.” The Convention also requires States Parties to “take all feasible measures to destroy anti-personnel mines in mined areas under its jurisdiction or control that are not under the control of the State Party concerned.” Each State Party must “as soon as possible” ensure that these mined areas “are perimeter marked, monitored and protected by fencing or other means, to ensure the effective exclusion of civilians, until all anti-personnel mines contained therein have been destroyed.”
    Each State Party must render these mined areas no longer dangerous “as soon as possible but not later than 10 years after the entry into force of this Convention for that State Party.
    If a State Party believes that it will be unable to destroy or ensure the destruction of all anti-personnel mines in mined areas within 10 years, "it may submit a request ... for an extension of the deadline for completing the destruction of such anti-personnel mines, for a period of up to ten years". The Convention requires States Parties to "take all feasible measures to ensure that the extension of the deadline is not used as a means of delaying the destruction of anti-personnel mines in mined areas.
    `,
    bodyText3: `What challenges remain? 
    A number of States Parties that are in the process of fulfilling their mine clearance obligation have been granted extended deadlines to address the remaining contamination. Some of these States have been carrying out clearance for decades, and will take them several years more to fulfill their obligation.
    Many States Parties that had declared having fulfilled their mine clearance obligation have discovered previously unknown or are experiencing newly mined areas. 
    Some States are experiencing new contamination from anti-personnel mines of an improvised nature. Fulfilling obligations will require effective use of the full range of methods to release suspected mined areas, including non-technical survey, technical survey and manual/mechanical clearance. Many States Parties must still undertake or complete the task of making every effort to identify all areas in which anti-personnel mines are known or suspected to be emplaced.
    `,
  },
  {
    id: 3,
    imageSource: `https://landportal.org/sites/landportal.org/files/styles/220heightmax/public/Icbl_english.jpg?itok=2JgvjcjK`,
    titleText: `International Campaign to Ban Landmines`,
    subTitleText: `What Is a Landmine?`,
    bodyText1: `Antipersonnel landmines are explosive devices designed to be detonated by the presence, proximity, or contact of a person. Placed under or on the ground, they can lie dormant for years and even decades until a person or animal triggers their detonating mechanism. Incapable of distinguishing between the footfall of a soldier and that of a child, antipersonnel mines cannot be aimed. They indiscriminately kill or injure civilians, aid workers, peacekeepers, and soldiers alike. They pose a threat to the safety of civilians during conflicts and long afterwards. 
    Made of plastic, metal, or other materials, they contain explosives and sometimes pieces of metal or other objects meant to cause additional injury. They can be activated by direct pressure from above, by pressure put on a wire or filament attached to a pull switch, or even simply by the proximity of a person within a predetermined distance.`,
    bodyText2: `Antipersonnel landmines claim victims across the globe each day. When triggered, a landmine unleashes unspeakable destruction, often destroying one or more limbs and projecting metal and debris into the wound, as well as causing burns, blindness, or other life-long injuries. Sometimes the victim dies from the blast, due to loss of blood or because they don't get to medical care in time. Those who survive and receive medical treatment often require amputations, long hospital stays, multiple operations, and extensive rehabilitation. 
    Stepping on a blast antipersonnel mine will invariably cause severe foot and leg injuries, as well as secondary infections usually resulting in amputation. Fragmentation mines project hundreds of metal fragments, showering the victim with deep wounds. Bounding fragmentation mines are more powerful versions: they spring up about 1 meter and then explode, firing metal fragments to a large radius at waist height.`,
    bodyText3: `The Mine Ban Treaty defines an antipersonnel mine as: "a mine designed to be exploded by the presence, proximity or contact of a person and that will incapacitate, injure or kill one or more persons." (Article 2.1) Nobody knows how many mines are in the ground worldwide. But the actual number is less important than their impact; it can take only a few mines or the mere suspicion of their presence to render a patch of land unusable.`,
  },
  {
    id: 4,
    imageSource: `https://upload.wikimedia.org/wikipedia/commons/3/35/Logo_of_the_United_Nations.png`,
    titleText: `United Nations Office for Disarmament Affairs`,
    subTitleText: `Landmines`,
    bodyText1: `Landmines come in two varieties: anti-personnel and anti-vehicle mines. Both have caused great suffering in the past decades. Anti-personnel landmines are prohibited under the Convention on the Prohibition of the Use, Stockpiling, Production and Transfer of Anti-Personnel Mines and on Their Destruction (or Mine Ban Convention), adopted in 1997. More than 150 countries have joined this treaty. Its positive impact includes a marked reduction of casualties, an increased number of mine-free States, destroyed stockpiles and improved assistance to victims.
    The Secretary-General calls on all countries to also regulate the use of anti-vehicle landmines. Such weapons continue to cause many casualties, often civilian. They restrict the movement of people and humanitarian aid, make land unsuitable for cultivation, and deny citizens access to water, food, care and trade.`,
    bodyText2: `Every day, people die or lose limbs from stepping on a landmine. Mostly in countries at peace - and the majority of victims are civilians. The Anti-personnel Landmine Convention, or the Mine Ban Convention, addresses this scourge. It bans the stockpiling, transfer and use of anti-personnel landmines, requires countries to clear them on their territory, while prescribing States in a position to do so to assist affected countries.
    In the 1980s, the use of anti-personnel landmines was regulated under the CCW treaty. But many countries wanted a complete ban. The ensuing Mine Ban Convention has been joined by three-quarters of the world's countries. Since its inception more than a decade ago, it has led to a virtual halt in global production of anti-personnel mines, and a drastic reduction in their deployment.`,
    bodyText3: ` More than 40 million stockpiled mines have been destroyed, and assistance has been provided to survivors and populations living in the affected areas. Vast numbers of mined and suspected hazardous areas have been declared free of landmines and released for productive use. As a result of these efforts, the number of casualties has sharply declined. Other welcome trends include: increases in national capacity to manage complex mine action programmes; the great progress in framing victim assistance in the wider context of disability; and the development of improved risk-reduction tools. The Mine Ban Convention has been a central framework for States in conducting mine action activities that led to all these remarkable achievements.
    However, well over 10 million stockpiled mines await destruction. Massive tracts of land are still infested and thus too dangerous for productive use. Tens of thousands of victims and their families have not yet received adequate support. The presence of mines continues to impede social and economic development.`,
  },
  // {
  //   id: 5,
  //   imageSource: `https://www.mineaction.org/sites/default/files/promobox/screen_shot_2018-07-16_at_4.51.27_pm_0.png`,
  //   titleText: `Mine Action Support Group`,
  //   subTitleText: `Bounding AP Mines`,
  //   bodyText1: `Most bounding fragmentation AP mines are cylindrical in shape, with a single tubular fuse or a number of prongs sticking out from the top. They are typically around 15 cm in diameter and 28 cm in height.When these mines are laid it is common to see only the prongs sticking out above the soil. These
  //   mines are usually tan, olive, black, brown, and green, or are left unpainted. It is not uncommon for the spikes to be left as unpainted natural metal.`,
  //   bodyText2: `Bounding fragmentation AP mines are generally triggered by pressure on tripwires and/or direct pressure. When tripwires (usually of fine wire) are used, they can run as far as 30 meters from the mines`,
  //   bodyText3: `Once triggered, an initial charge lifts the mine up to waist height before the main charge detonates. Upon detonation, the explosion shoots out metal fragments in a 360-degree horizontal arc. These fragments can inflict lethal injuries at distances of up to 35 meters or more from the landmine, and can cause severe injuries at more than 100 meters. The fragments can also cause damage to vehicles and other equipment.`,
  // },
]